import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
// import image from '../../src/pages/warjono.jpeg'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  var i = 0;
  var txt = 'Selamat Hari Raya Idul Fitri 1 Syawal 1444 Hijriah. Mohon Maaf Lahir dan Batin 🙏';
  var speed = 50;

  const [showImage, setShowImage] = useState(false);

  function typeWriter() {
    if (i < txt.length) {
      document.getElementById("text").innerHTML += txt.charAt(i);
      i++;
      setTimeout(typeWriter, speed);
    }
    else {
      setShowImage(true)
    }
  }
  useEffect(() => {
    typeWriter();
  }, []);



  return (
    <>
      <Head>
        <title>Selamat Hari Raya Idul Fitri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ visibility: showImage ? 'visible' : 'hidden' }} className="pyro">
        <div className="before"></div>
        <div className="after"></div>
      </div>
      <main className={styles.main}>

        <div className={styles.description}>
          <h1 id='text'></h1>
        </div>
        <img style={{ width: '100%', height: '100%', visibility: showImage ? 'visible' : 'hidden' }} src="/taqob5.png" alt="" />
        <br />
        <h5 style={{ visibility: showImage ? 'visible' : 'hidden' }}>~ Brian Esa & Keluarga ~</h5>

      </main>
    </>
  )
}
